services:
  db:
    image: postgres:alpine
    environment: { POSTGRES_PASSWORD: postgres }
    ports: [ '5432:5432' ]
    restart: always
  adminer:
    image: adminer
    ports: [ '8080:8080' ]
    restart: always
